### ISSUE TITLE
Expose via new callback argument vs. new function

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-json-parse-with-source#1]
This proposal currently suggests invoking `JSON.parse` reviver functions with additional arguments, but @erights noted that he cannot remember any spec change that added arguments to either built-in function or a callback invoked by a built-in function. The specification itself has nothing to say on this issue; a [note](https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects) recommending that implementations do not add custom parameters to built-in functions is the closest I could find:
> Implementations that add additional capabilities to the set of built-in functions are encouraged to do so by adding new functions rather than adding new parameters to existing functions.

If the committee is uncomfortable with providing new arguments to `JSON.parse` reviver functions, then we would need a shift to something like `JSON.parseWithSource(source, reviver)` or `JSON.parseWithSource(source, options)`.

**Comment by mathiasbynens** [comment]
There is precedent for this elsewhere on the Web Platform, e.g. when `addEventListener` started supporting a third argument for the `options` bag. I think it’s perfectly fine to make such a change.

**Comment by gibson042** [comment]
The committee seemed most comfortable with adding arguments to existing callback invocation.

**Comment by gibson042** [comment]
No objections today either; I'm considering this resolved.
