### ISSUE TITLE
performance impact with 1-million json.parse calls

### ISSUE THREAD

**Issue by kaizhu256** [tc39/proposal-json-parse-with-source#16]
thread is slightly off-topic as real-world-scenario is parsing-json in c#/unity rather than javascript, but might be informative.

context:
[RogueTech](https://github.com/BattletechModders/RogueTech) is community-mod for rpg-videogame BATTLETECH, and infamous for taking forever to startup+load - around 4 minutes on 2018 mac-mini.

after some instrumentation-patching, found out game+mod calls `JSONSerializationUtility.RehydrateObjectFromDictionary()` 930,000 times from program-startup to loading saved game (game has ~4000 json-files for various rpg-stats).

the 1-million calls in c# to parse json may have contributed to long load-time, but i have no proof.  but just wanted to make aware of real-world application making high number of json-parsing calls and suffering [maybe unrelated] performance issues.

**Comment by gibson042** [comment]
Thank you for the information. We'll consult it as necessary, but close the issue for now to avoid clutter.
