### ISSUE TITLE
bigint ergonomics of user-function vs options-object

### ISSUE THREAD

**Issue by kaizhu256** [tc39/proposal-json-parse-with-source#17]
apologies for revisiting #5 (add an options object to JSON.parse and JSON.stringify)

i think this proposal's primary motivation is parsing bigint? imo options-object like `{ bigintIfTooBig: true }` remains more ergonomic (and less error-prone):

```js
// options-object
JSON.parse(
    "[ 1, 12345678901234567890, 3, \"foo\" ]",
    {
        bigintIfTooBig: true,
        bigintDigitLimit: 50 // security-check
    }
);
// [ 1, 12345678901234567890n, 3, "foo" ]

// user-function
JSON.parse(
    "[ 1, 12345678901234567890, 3, \"foo\" ]",
    function (key, val, {source}) {
        if (
            typeof val === number
            && (val === Number.MAX_SAFE_INTEGER || val === Number.MIN_SAFE_INTEGER)
        ) {
            // security-check
            if (source.length > 50) {
                throw new Error("bigint buffer-overflow");
            }
            return bigint(source);
        }
        return val;
    }
);
// [ 1, 12345678901234567890n, 3, "foo" ]
```

roundtripping is more ergonomic as well:

```js
let data;
data = [ 1, 12345678901234567890n, 3, "foo" ];
data = JSON.stringify(
    data,
    {
        allowBigint: true
    }
);
// "[ 1, 12345678901234567890, 3, \"foo\" ]"
data = JSON.parse(
    data,
    {
        bigintIfTooBig: true,
        bigintDigitLimit: 50
    }
);
// [ 1, 12345678901234567890n, 3, "foo" ]
```

**Comment by gibson042** [comment]
Thank you for the feedback, but that approach is too narrow for the goals of this proposal, which aims to support fine-grained practitioner control of deserialization now (e.g., which output values are Number vs. BigInt), and also future use cases such as BigDecimal. Refer to https://github.com/tc39/proposal-json-parse-with-source/issues/12#issuecomment-704441889 for the currently anticipated shape of serialization.
