### ISSUE TITLE
Are there any implementations yet?

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-json-parse-with-source#36]
Has this proposal been implemented anywhere yet (e.g. via a polyfill)? Thanks!

**Comment by mathiasbynens** [comment]
I've linked to implementation tracking bugs here: https://github.com/tc39/proposal-json-parse-with-source/issues/15#issue-664090651 V8 has an implementation behind the `--harmony-json-parse-with-source` flag.

**Comment by rauschma** [comment]
Thanks @mathiasbynens!
